# Generated by Django 3.0.5 on 2020-04-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfoModel',
        ),
    ]
